apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - name: angular-app
        image: self1.azurecr.io/self1/cs_app:ui_app1
        imagePullPolicy: Always
        ports:
        - containerPort: 90
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: angular-app
    k8s-app: angular-app
  name: angular-app
  annotations:
    service.beta.kubernetes.io/azure-pip-name: da62b626-cca3-4069-b002-cdf040823d58
    service.beta.kubernetes.io/azure-load-balancer-resource-group: test_env
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 90
  type: LoadBalancer
  selector:
    app: angular-app
