apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - name: angular-app
        image: self1.azurecr.io/self1/cs_app:ui_app1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: angular-app
    k8s-app: angular-app
  name: angular-app
  annotations:
    service.beta.kubernetes.io/azure-pip-name: 317b483f-c5cb-45ef-8f79-318fd65f872f
    service.beta.kubernetes.io/azure-load-balancer-resource-group: MC_test_env_test_aks_centralindia
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer
  selector:
    app: angular-app
